global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: core-api
    static_configs:
      - targets: ['core-api:3001']
    metrics_path: /metrics

  - job_name: offshore-collector
    static_configs:
      - targets: ['offshore-collector:3002']
    metrics_path: /metrics

  - job_name: payout-orchestrator
    static_configs:
      - targets: ['payout-orchestrator:3003']
    metrics_path: /metrics

  - job_name: reconciliation-worker
    static_configs:
      - targets: ['reconciliation-worker:3004']
    metrics_path: /metrics
